# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86cc70790eaa7e7e7ed5275b62ea895bab9a19d7f18468370f0294363953a6dd8b09ca27cfe102c265a76a945ed236894fe62b108f858d51d5a9f3ae1c35f8af

test:
  secret_key_base: d3d4c3a2da3724c3a5811753b7297f1e9265790abf43d194eed134e27f25c62bc968dfa26c29d987082de4fa3e5c99297670eddea75dac08dcd681bd6b6415ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
